//
//  EmotionFlowerViewModel.swift
//  EmotionTrack
//
//  Created by Іван Джулинський on 07.01.2024.
//

import SwiftUI

final class EmotionsFlowerViewModel: ObservableObject {
    
    @Published var selectedColor: Color = .yellow
    
    @Published var firstPetalColor: Color = .white
    @Published var secondPetalColor: Color = .white
    @Published var thirdPetalColor: Color = .white
    @Published var fourthPetalColor: Color = .white
    @Published var fifthPetalColor: Color = .white
    @Published var sixthPetalColor: Color = .white
    @Published var seventhPetalColor: Color = .white
    @Published var eighthPetalColor: Color = .white
    
    var colors: [Color] {
       return [firstPetalColor, secondPetalColor, thirdPetalColor, fourthPetalColor, fifthPetalColor, sixthPetalColor, seventhPetalColor, eighthPetalColor].removingDuplicates()
    }
    
    func getResult() -> [ColorDetails] {
        var result: [ColorDetails] = []
        for color in colors {
            result.append(getColorDetails(for: color))
        }
        return result
    }
    
    @Published var showingAlert = true
    
    private func getColorDetails(for color: Color) -> ColorDetails {
        switch color {
        case .yellow:
            return ColorDetails(emoji: "🤩", title: "Ecstasy", description: "Ecstasy is a state of intense happiness, joy, and satisfaction. It is often described as a feeling of euphoria where you feel as if you are on top of the world. \nIt can be caused by a variety of factors, such as: \n• Spiritual experiences: Prayer, meditation, or other religious practices can lead to a sense of oneness with something greater than oneself, which can cause ecstasy. \n• Creativity: Art, music, and other creative pursuits can give people a sense of fulfillment and satisfaction, which can lead to ecstasy.\n• Love: Deep feelings of love for a partner, child, or other person can lead to ecstasy. \nIt is important to note that ecstasy is a temporary state. It cannot last forever, and it is important not to chase it constantly.")
            
        case Color("Lemon"):
            return ColorDetails(emoji: "😊", title: "Joy", description: "Joy is a positive emotion characterized by feelings of happiness, satisfaction, pleasure, and elation. It can occur in response to various events, such as: \n• Achieving a goal \n• Receiving good news \n• Spending time with loved ones \n• Experiencing something new and exciting \n• Helping others \n• Just enjoying the beauty of the world \nJoy has many benefits for our health and well-being: \n• Strengthens the immune system \n• Reduces stress levels \n• Improves heart function \n• Reduces the risk of depression \n• Increases energy levels \n• Increases productivity \n• Strengthens relationships")
            
        case Color("Canary"):
            return ColorDetails(emoji: "😌", title: "Serenity", description: "Serenity is an emotional state characterized by a sense of peace, quiet, and deep contentment. It is a state where a person feels balanced, happy, and free from anxiety. \nHere are some key characteristics of the emotion of serenity: \n• Inner peace: The absence of worries, fears, or anxiety. \n• A sense of unity: A sense of connection to oneself, nature, or something larger than oneself. \n• Deep satisfaction: Feelings of joy, happiness, and gratitude. \n• Clarity of mind: The ability to think clearly, to see the situation as a whole, and to make good decisions. \n• Body relaxation: The absence of muscle tension, a feeling of lightness and comfort. \nCalmness has many benefits for our health and well-being: \n• It reduces stress and anxiety. \n• Improves sleep. \n• Strengthens the immune system. \n• Increases creativity and productivity. \n• Helps us cope better with difficulties. \nCalmness is a valuable state that each of us can learn to experience. By practicing different methods and making changes in our lifestyle, we can experience this state more often and live a happier and more fulfilling life.")
            
        case Color("Dark Pastel Green"):
            return ColorDetails(emoji: "💖", title: "Admiration", description: "Admiration is an emotion that occurs when we see something or someone that we consider outstanding, impressive, or worthy of emulation. It is a feeling of respect and admiration that can be directed toward people, animals, objects, ideas, or achievements. \nAdmiration can have many positive effects, for example: \n• Motivates us to achieve more. \n• Helps us see the beauty in the world. \n• Strengthens our relationships with other people. \n• Makes our life more rich and interesting. \nHow to develop a hobby? \n• Be open to new things. \n• Pay attention to what inspires you. \n• Look for people you admire. \n• Don't be afraid to express your passion. \nAdmiration is a powerful emotion that can enrich our lives. It can motivate us to improve ourselves, help us see the beauty in the world, and strengthen our relationships with others.")
            
        case Color("Screamin Green"):
            return ColorDetails(emoji: "🤝", title: "Trust", description: "Trust is a multifaceted emotion that is based on the belief that another person or system will act in our best interests without harming or deceiving us. It is closely related to feelings of safety, confidence, and comfort. \nThe importance of trust: \n- Strengthens relationships: \n• Facilitates communication \n• Allows for collaboration \n• Creates a sense of community \n- Improves quality of life: \n• Reduces stress \n• Improves mental health \n• Promotes economic development \nHow to build trust: \n- Consistency: \n• Keep your promises \n• Act responsibly \n• Being honest \n- Transparency: \n• Share information \n• Be open to communication \n• Explain your actions \n- Empathy: \n• Understand the feelings of others \n• Showing concern \n• To be attentive \nTrust is a fragile emotion that needs to be nurtured and protected. It is the basis for healthy relationships, successful cooperation and a happy life.")
            
        case Color("Mint Green"):
            return ColorDetails(emoji: "😌", title: "Acceptance", description: "Acceptance is an emotion characterized by a sense of calm and contentment with what is. It is a state where you can fully accept yourself, others, and the world around you as it is. \nAcceptance is often viewed as a positive emotion, and it can be associated with a number of beneficial mental and physical health outcomes. For example, acceptance has been linked to reduced levels of stress, anxiety, and depression. It has also been linked to increased self-esteem, resilience, and happiness.")
            
        case .green:
            return ColorDetails(emoji: "😱", title: "Terror", description: "Terror is an intense fear that is caused by the threat of violence or death. It is an emotion that can be triggered by a variety of factors, including: \n• Violence: Terror can be triggered by directly experiencing or witnessing violence. \n• Threat: Terror can be triggered by a sense of threat, even if violence has not yet occurred. \n• Uncertainty: Terror can be caused by uncertainty about what might happen. \n- Lack of control: Terror can be caused by a feeling of lack of control over a situation. \nCoping with terror can be difficult, but there are some things you can do to help yourself: \n• Get help: If you are experiencing terror, it is important to seek help from friends, family, or a counselor. \n• Talk about your feelings: Talking about what you are going through can help you cope with your emotions. \n• Practice relaxation techniques: Relaxation techniques such as deep breathing or meditation can help you calm down. \n• Avoid triggers: If there are certain things that remind you of terror, try to avoid them. \n• Focus on the positive: Focus on the good things in your life to help you feel more positive.")
            
        case Color("Islamic Green"):
            return ColorDetails(emoji: "😨", title: "Fear", description: "Fear is an emotion that occurs in response to a perceived threat. It is a natural response to danger that helps us survive. \nSymptoms of fear: \n• Physical: heart palpitations, sweating, trembling, muscle tension, nausea, dizziness. \n• Psychological: worry, anxiety, panic, anger, irritability, feeling of helplessness. \n• Behavioral: avoidance, flight, numbness, expecting the worst. \nHow to overcome fear: \n• Psychotherapy: Cognitive behavioral therapy (CBT) can help you change negative thoughts and behaviors associated with fear. \n• Medication: In some cases, antidepressants or anxiolytics may be prescribed. \n• Relaxation techniques: meditation, yoga, deep breathing can help you relieve anxiety and fear. \n• Healthy lifestyle: getting enough sleep, exercising, and eating a balanced diet can help you cope with stress better.")
            
        case Color("Dark Sea Green"):
            return ColorDetails(emoji: "😧", title: "Apprehension", description: "Apprehension is an emotion that describes feelings of worry, anxiety, or anticipation of something unpleasant. It can be mild nervousness or intense fear, depending on the situation. \nHere are some key characteristics of apprehension: \n• Negative orientation: Apprehension is always associated with the expectation of something negative, such as failure, danger, or an unpleasant event. \n• Uncertainty: This emotion usually occurs when a person is not sure what exactly will happen, but feels that it could be something bad. \n• Physiological symptoms: Apprehension can be accompanied by physiological symptoms such as heart palpitations, sweating, muscle tension, or nausea. \n• Effects on behavior: Apprehension can cause a person to avoid certain situations or people, or to act more cautiously than usual. \nWays to overcome apprehension: \n• Identifying triggers: What exactly triggers your apprehension? Once you know your triggers, you can start working on overcoming them. \n• Relaxation: Practicing relaxation techniques, such as deep breathing, meditation, or yoga, can help you reduce apprehension symptoms. \n• Positive thinking: Focus on positive outcomes and visualize success. \n• Support: Talk to a friend, family member, or counselor about your feelings. \nIt is important to remember that apprehension is a normal emotion that everyone experiences from time to time.")
            
        case Color("Pacific Blue"):
            return ColorDetails(emoji: "🫢", title: "Amazement", description: "Amazement is an emotion that arises in response to something unexpected, new, or incomprehensible. It can be something pleasant, such as an unexpected gift, or something unpleasant, such as a sudden accident. \nSigns of surprise: \n• Eyes wide open \n• Raised eyebrows \n• Open mouth \n• Holding your breath \n• Non-verbal exclamations such as \"Oh, my!\" or \"Wow!\" \nSurprise can be both positive and negative. Positive surprise can lead to joy, delight, or amazement. Negative surprise can lead to fear, shock, or disappointment.")
            
        case .cyan:
            return ColorDetails(emoji: "😮", title: "Surprise", description: "Surprise is a sudden and short-lived emotional reaction to an unexpected event or situation. It can be caused by both positive and negative events, such as: \n• An unexpected gift \n• Good news \n• A sudden meeting with a friend \n• An accident \n• A loud sound \nSurprise can have both positive and negative consequences. On the one hand, it can motivate people to learn new things and explore the world. On the other hand, it can lead to confusion and inability to act. \nSurprise is a normal and natural emotion that is part of our lives. It helps us adapt to changing environmental conditions and learn new things.")
            
        case Color("Columbia Blue"):
            return ColorDetails(emoji: "😵‍💫", title: "Distraction", description: "Distraction is a condition where your attention is drawn away from something important or interesting. It can be caused by a variety of factors, such as: \n• External stimuli: Loud noises, bright visual cues, or other people talking or doing something interesting. \n• Internal stimuli: Wandering thoughts, feelings of anxiety or boredom, or physical discomfort. \n• Information overload: When you try to process too much information at once, you may feel distracted and unable to focus on one thing. \nHow to cope with the emotion of distraction: \n• Identify the cause: Before you can deal with distraction, you need to identify what is causing it. \n• Eliminate distractions: As much as possible, try to eliminate distractions from your environment. \n• Focus on one task: Focus on one task at a time and don't switch to other tasks until you've finished the first one. \n• Take breaks: If you feel distracted, take short breaks to rest and focus. \n• Practice mindfulness: Mindfulness can help you focus on the present moment and not get distracted by wandering thoughts.")
            
        case Color("Medium Blue"):
            return ColorDetails(emoji: "☹️", title: "Grief", description: "Grief is a complex emotion characterized by feelings of sadness, loss, grief, and despair. It can be triggered by a variety of factors, such as the death of a loved one, the end of a relationship, job loss, or serious illness. \nGrief is a normal and healthy emotion. It is important to allow yourself to grieve and process the loss. There is no right or wrong way to grieve, and everyone experiences it differently. \nThere are many ways to cope with grief. Some people find it helpful to talk to friends and family members, while others prefer to grieve alone. Some people find it helpful to participate in support groups or grief counseling. There are also books, websites, and other resources that can help people cope with grief. \nIf you are experiencing grief, it is important to reach out for support. Talk to a friend, family member, therapist, or other trusted friend. There are also many online resources that can help you.")
            
        case .indigo:
            return ColorDetails(emoji: "😭", title: "Sadness", description: "Sadness is a normal human emotion characterized by feelings of grief, disappointment, and loss. It can be caused by various factors, such as \n• The death of a loved one \n• The end of a relationship \n• Job loss or loss of finances \n• Health problems \n• Stress \n• Loneliness \n• Boredom \n• If you are feeling sad, it is important to seek support from friends, family, or a therapist. There are also many things you can do on your own to cope with sadness, such as: \n• Exercise \n• Getting enough sleep \n• Eating a healthy diet \n• Spending time with loved ones \n• Doing activities that you enjoy \n• Practicing relaxation techniques such as yoga or meditation")
            
        case Color("Light State Blue"):
            return ColorDetails(emoji: "😔", title: "Pensiveness", description: "Pensiveness is a state of deep thought or reflection. It is often associated with feelings of melancholy or sadness, but can also be triggered by feelings of peace or contentment. Brooding is often considered a positive emotion because it can lead to creativity and self-understanding. \nHere are some ways to express brooding: \n• Facial expression: A brooding person often has a soft, focused expression. Their eyes may be staring off into the distance and they may appear lost in thought. \n• Body language: A brooding person may adopt a relaxed posture, such as sitting with their chin propped up or lying on their back. They may also cross their arms over their chest or clench their hands into fists. \n• Speech: A thoughtful person may speak in a quiet, measured tone. They may use language that is reflective or philosophical. \nThoughtfulness can be a rewarding emotional experience. It can allow us to slow down and appreciate the beauty of the world around us. It can also help us to better understand ourselves and our place in it.")
            
        case Color("Deep Magenta"):
            return ColorDetails(emoji: "😠", title: "Loathing", description: "Loathing is a strong emotion that occurs in response to something that is perceived as disgusting, horrible, or repulsive. It can be triggered by physical stimuli, such as an unpleasant smell or taste, or by moral considerations, such as disgust at cruelty or injustice. \nIt is important to note that disgust is a subjective emotion. What disgusts one person may not disgust another. Disgust can also change over time and under the influence of cultural factors. \nDisgust can be a complex emotion, but it can play an important role in our lives. It can protect us from danger, motivate us to follow moral norms and rules, and express our emotions.")
            
        case Color("Pink Flamingo"):
            return ColorDetails(emoji: "🤢", title: "Disgust", description: "Disgust is an emotion caused by something disgusting or physically repulsive. It can be caused by something that is seen, smelled, tasted, felt, or even heard. Disgust is often accompanied by physical symptoms such as nausea, vomiting, chills, and sweating. \nThe evolutionary purpose of disgust is to protect us from harmful substances. Things that tend to be disgusting, such as spoiled food, feces, and bodily fluids, often contain bacteria or other harmful microorganisms that can make us sick. Disgust can also be caused by things that are dangerous or harmful in other ways, such as toxic substances, hazardous waste, and animals. \nDisgust can be a powerful emotion, and it can have a significant impact on our lives. It can make us avoid certain foods, people, and situations. It can also lead to feelings of disgust, revulsion, and even hatred. \nHowever, disgust can also be a useful emotion. It can help us to protect ourselves from harm, and it can motivate us to follow good hygiene and sanitation practices. It can also help us shape social norms and values.")
            
        case Color("Cotton Candy"):
            return ColorDetails(emoji: "🥱", title: "Boredom", description: "Boredom is an emotional state characterized by apathy, lack of stimulation, and lack of motivation. It can be a temporary state that occurs when we are uninterested or dislike what we are doing, or a deeper state that indicates that we lack meaning or purpose in life. \nBoredom can be a negative experience, but it can also be an opportunity for growth. When we are bored, we have a chance to explore our interests, values, and goals. We can also use this time for creativity and self-reflection. \nIt is important to remember that boredom is a normal human emotion. Everyone feels bored from time to time. If you feel bored, don't blame yourself. Just find a way to turn this emotion into something positive. \nHow to deal with boredom: \n• Find something that interests and excites you. \n• Set goals and work towards them. \n• Spend time with people you like. \n• Help others. \n• Go out into nature. \n• Try something new.")
            
        case Color("Free Speech Red"):
            return ColorDetails(emoji: "🤬", title: "Rage", description: "Rage is a strong emotion that can be triggered by a variety of factors, such as frustration, pain, or feeling threatened. When people feel angry, they may experience physical symptoms such as a rapid heartbeat, muscle tension, or sweating. They may also snap at others verbally or physically or withdraw from others. \nAnger can be a destructive emotion, but it can also be a motivating force. Anger can help people stand up for themselves or others, and it can lead to positive change. However, it is important to learn how to manage anger in a healthy way so that it does not lead to problems in a person's life. \nHere are some tips on how to deal with anger: \n• Recognize your triggers: What makes you angry the most? Once you know your triggers, you can start avoiding them or develop strategies to deal with them. \n• Take a time out: If you feel yourself getting angry, give yourself a few minutes to calm down before saying or doing something you might regret. Try taking a deep breath, counting to ten, or going for a walk. \n• Express your anger in a healthy way: If you need to express your anger, do so in a way that doesn't hurt you or others. This may include talking to someone you trust, journaling, or exercising. \n• Practice relaxation skills: Relaxation techniques such as deep breathing, yoga, or meditation can help you calm down and reduce stress. \n• Get professional help: If you struggle with anger management on your own, you may find it helpful to seek professional help. A therapist can teach you coping mechanisms and help you understand the root of your anger.")
            
        case Color("Red"):
            return ColorDetails(emoji: "😡", title: "Anger", description: "Anger is a normal human emotion that can be triggered by a variety of factors, such as stress, frustration, or feeling threatened. When people feel angry, they may experience physical symptoms such as a rapid heartbeat, muscle tension, or sweating. They may also snap at others verbally or physically or withdraw from others. \nAnger can be a destructive emotion if left unchecked. However, it can also be a motivating force for positive change. For example, anger can drive people to stand up for what they believe in or take action to solve a problem. \nHere are some healthy ways to deal with anger: \n• Express your anger in a healthy way, such as by exercising or journaling. \n• Talk to someone you trust about what is making you angry. \n• Practice relaxation techniques such as deep breathing or meditation. \n• Take breaks when you feel angry. \n• Avoid making decisions when you are angry.")
            
        case .red:
            return ColorDetails(emoji: "😒", title: "Annoyance", description: "Annoyance is a feeling of mild to moderate anger or dissatisfaction. It is often triggered by something small or what is perceived as a minor insult or obstacle. For example, you might get irritated if someone is late for a meeting, interrupts you while you are talking, or does something annoying like clicking their tongue. \nIf you feel irritated, there are a few things you can do to deal with it: \n- Identify the source of your irritation: What exactly is causing you to be irritated? Once you've identified the source, you can start working on resolving it. \n• Take a break: If you feel like you're about to explode, take a break for a few minutes to calm down. Go for a walk, listen to music, or take a few deep breaths. \n• Express your irritation in a healthy way: If you can, talk to someone about what's bothering you. This can help you feel better and give you a different perspective. \n• Practice relaxation techniques: Relaxation techniques such as yoga, meditation, or massage can help reduce stress and improve mood. \n• Get enough sleep: Most adults need 7 to 8 hours of sleep a night. \n• Eat healthy foods: A healthy diet can help you maintain stable blood sugar levels and prevent mood swings. \n• Seek professional help: If you experience irritability for a long period of time or if it interferes with your daily life, seek professional help. A therapist can help you identify the cause of your irritation and develop strategies for coping with it.")
            
        case .orange:
            return ColorDetails(emoji: "🧐", title: "Vigilance", description: "Vigilance is a state of heightened attention and readiness for action. It is a state of high awareness and arousal. Vigilance can be triggered by a number of factors, including danger, excitement, or anticipation. \nWhen people are in a state of alertness, their pupils dilate, their heart rate and respiration increase, and their muscles tense. These physiological changes prepare the body for action. \nVigilance can be useful in situations where you need to be on the alert. For example, if you are walking through a dangerous neighborhood, vigilance can help you to be aware of potential dangers. Vigilance can also be helpful in situations where you are trying to concentrate, such as when taking an exam or driving a car. \nHowever, vigilance can also be exhausting. When people are in a state of alertness for a long period of time, they can feel anxious, irritable, and tired. In some cases, prolonged alertness can lead to sleep problems and difficulty concentrating. \nIf you're feeling alert, there are a few things you can do to relax: \n• Take a few deep breaths and exhale slowly. \n• Focus on relaxing your muscles, starting with your toes and working your way up your body. \n• Focus on a soothing image or sound. \n• Drink a cup of herbal tea or take a warm bath.")
            
        case Color("Texas Rose"):
            return ColorDetails(emoji: "🫠", title: "Ancipation", description: "Anticipation is an emotion that occurs before an event that is about to happen. It can be either positive or negative, depending on how we perceive the event. \nAnticipation can influence our behavior \n• Increase motivation: When we expect something pleasant to happen, we are more motivated to make an effort to achieve it. \n• Decrease motivation: When we anticipate something unpleasant, we may avoid it or put it off until later. \n• Influence our perception: Expectations can affect the way we perceive events. For example, if we expect an exam to be difficult, it will seem even more difficult than it actually is. \nHere are some tips on how to better manage expectations: \n• Focus on what you can control. If you're expecting something unpleasant, think about what you can do to prepare for it or reduce its impact. \n• Practice relaxation techniques. This can help you reduce anxiety and worry. \n• Don't get hung up on waiting. Focus on what is happening now and enjoy the moment. \nWaiting is a normal part of life. By learning to better manage this emotion, we can reduce its negative impact on our lives.")
            
        case Color("Peach"):
            return ColorDetails(emoji: "🤔", title: "Interest", description: "Interest is a positive emotion that occurs when we encounter something new, exciting, or uncertain. It is characterized by feelings of anticipation and excitement. Curiosity can be triggered by a wide range of things, such as new ideas, experiences, people, or places. \nWhen we feel curious, our pupils dilate, our heart rate and blood pressure rise. This is because our body is preparing to explore and investigate the source of our interest. Curiosity can also motivate us to take action, prompting us to seek out more information or engage in new activities. \nCuriosity plays an important role in learning and development. It helps us to explore the world around us and absorb new knowledge. Curiosity can also help us to be more creative and inventive, as it encourages us to think outside the box and consider new possibilities.")
            
        default:
            return ColorDetails(emoji: "😬", title: "Oops", description: "Something went wrong! Please, try again.")
        }
    }

}
